version: '3.1'

services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog-db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306